CREATE DATABASE QL_DTDD1
GO
USE QL_DTDD1
GO

CREATE TABLE LOAI
(
	MALOAI INT NOT NULL,
	TENLOAI NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_LOAI PRIMARY KEY(MALOAI)
)

CREATE TABLE SANPHAM
(
	MASP INT NOT NULL,
	TENSP NVARCHAR(50) NOT NULL,
	DUONGDAN VARCHAR(50) NOT NULL,
	GIA DECIMAL(18, 2) NOT NULL,
	MOTA NVARCHAR(100) NOT NULL,
	MALOAI INT NOT NULL,
	CONSTRAINT PK_SANPHAM PRIMARY KEY(MASP),
	CONSTRAINT FK_SANPHAM_LOAI FOREIGN KEY(MALOAI) REFERENCES LOAI(MALOAI)
)

CREATE TABLE KHACHHANG
(
	MAKH INT NOT NULL,
	HOTEN NVARCHAR(50) NOT NULL,
	DIENTHOAI VARCHAR(11) NOT NULL,
	GIOITINH NVARCHAR(10) NOT NULL,
	SOTHICH NVARCHAR(50) NOT NULL,
	EMAIL NVARCHAR(50) NOT NULL,
	MATKHAU VARCHAR(50) NOT NULL,
	CONSTRAINT PK_KHACHHANG PRIMARY KEY(MAKH)
)

CREATE TABLE GIOHANG
(
	MAGH INT NOT NULL,
	MAKH INT NOT NULL,
	MASP INT NOT NULL,
	SOLUONG INT NOT NULL,
	NGAY DATE NOT NULL,
	CONSTRAINT PK_GIOHANG PRIMARY KEY(MAGH),
	CONSTRAINT FK_GIOHANG_KHACHHANG FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH),
	CONSTRAINT FK_GIOHANG_SANPHAM FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP)
)

INSERT INTO LOAI VALUES
	(1, N'Nokia'),
	(2, N'Samsung'),
	(3, N'Motorola'),
	(4, N'LG'),
	(5, N'Oppo'),
	(6, N'Iphone'),
	(7, N'Bphone')

INSERT INTO SANPHAM VALUES
	(1, 'N701', 'N70.jpg', 2000000, N'Nâng cấp BN', 1),
	(2, 'N72', 'N72.jpg', 2100000, N'Nâng cấp BN, 2 màu Đen, Xám', 4),
	(3, 'N6030', 'N6030.jpg', 3000000, N'Nâng cấp BN, Gấp', 2),
	(4, 'N6200', 'N6200.jpg', 3200000, N'Nâng cấp BN, Màu Đen, Xám, Đỏ, Bạc', 5),
	(5, 'GalaxyA6', 'GalaxyA6.jpg', 5200000, N'Nâng cấp BN, Màu Đen, Xám, Đỏ, Bạc', 6),
	(6, 'GalaxyA9', 'GalaxyA9.jpg', 5500000, N'Nâng cấp BN, Màu Đen, Xám, Đỏ, Bạc', 4),
	(7, 'GalaxyJ5', 'GalaxyJ5.jpg', 6000000, N'Nâng cấp BN, Màu Đen, Xám, Đỏ, Bạc', 3),
	(16, 'MotoE5', 'MotoE5.jpg', 2300000, N'Unlimited Extra', 7),
	(17, 'MotoG7', 'MotoG7.jpg', 8000000, N'Unlimited Extra', 1);